default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password:

development:
  <<: *default
  database: tea02_development

test:
  <<: *default
  database: tea02_test

production:
  <<: *default
  database: tea02_production


